sudo: required
service:
  - docker

before_install:
  - docker build -t slewa/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true slewa/react-test nmp test

after_success:
  - docker build -t slewa/multi-client -f ./client
  - docker build -t slewa/multi-nginx -f ./nginx
  - docker build -t slewa/multi-server -f ./server
  - docker build -t slewa/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push slewa/multi-client
  - docker push slewa/multi-nginx
  - docker push slewa/multi-server
  - docker push slewa/multi-worker


